// Generated by tools/import-hymnary-spanish.ts — do not edit by hand.
// Public-domain Spanish hymn texts indexed by hymnary.org (each marked
// "Copyright: Public Domain" there). Harvested most-published-first.
// Attribution: Hymnary.org — see .notes/content-sources.md.
export const HYMNS_ES_HYMNARY = [
  {
    "t": "Divina Luz",
    "a": "J. B. Cabrera",
    "y": null,
    "th": null,
    "k": null,
    "bpm": null,
    "ts": null,
    "lang": "Spanish",
    "scr": "Salmos 43:3",
    "lic": "PD",
    "cong": 0,
    "chordPro": "Verse 1\nDivina Luz, con tu esplendor benigno,\nGuarda mi pie;\nDensa es la noche y áspero el camino;\nMi guía se.\nHarto distante de mi hogar estoy;\nQue al dulce hogar de las alturas voy.\n\nVerse 2\nAmargos tiempos hubo en que tu gracia\nNo suplique;\nDe mi valor fiando en la eficacia,\nNo tuve fe.\nMás hoy deploro aquella ceguedad;\nPréstame oh Luz, tu grata claridad."
  },
  {
    "t": "Grato es decir la historia",
    "a": "Kate Hankey · tr. Juan Bautista Cabrera Ivars",
    "y": null,
    "th": null,
    "k": null,
    "bpm": null,
    "ts": null,
    "lang": "Spanish",
    "scr": "Salmos 66:1-4",
    "lic": "PD",
    "cong": 0,
    "chordPro": "Verse 1\nGrato es decir la historia\ndel celestial favor,\nde Cristo y de su gloria,\nde Cristo y de su amor;\nMe agrada referirla,\npues sé que es la verdad;\ny nada satisface\ncual ella, mi ansiedad.\n\nChorus\n¡Cuán bella es esa historia!\nMi tema allá en la gloria\nserá la antigua historia\nde cristo y de su amor.\n\nVerse 2\nGrato es decir la historia\nque brilla cual fanal,\ny en glorias y portentos\nno reconoce igual;\nMe agrada referirla,\npues me hace mucho bien;\npor eso a ti deseo\ndecírtela también."
  },
  {
    "t": "Inmensa y sin Igual Piedad",
    "a": "Isaac Watts · tr. Anonymous",
    "y": null,
    "th": "Grace,Lament",
    "k": "E",
    "bpm": 76,
    "ts": "4/4",
    "lang": "Spanish",
    "scr": "Mateo 27:45-50",
    "lic": "PD",
    "cong": 0,
    "chordPro": "Verse 1\n¡Inmensa y sin igual piedad!\nJesús murió por mí;\nY por mi culpa vil sufrió\nLa muerte en la cruz.\n\nChorus\nAcuérdate, Señor Jesús;\nAcuérdate de mí;\nY por Tu muerte y Tu pasión,\n¡Oh, ten piedad de mí!\n\nVerse 2\nPor la maldad que hice yo,\nMurió el Redentor:\n¡Oh qué divina compasión!\n¡Qué infinito amor!\n\nVerse 3\nY tuvo que esconderse el sol\nEn negra confusión,\nAl ver morir al Salvador\nPor nuestra redención.",
    "parent": "Alas! and Did My Savior Bleed",
    "rel": "Spanish translation · tr. Anonymous"
  },
  {
    "t": "Lluvias de Gracia",
    "a": "D. W. Whittle · tr. W. S. Scott",
    "y": null,
    "th": null,
    "k": null,
    "bpm": null,
    "ts": null,
    "lang": "Spanish",
    "scr": "Ezequiel 34:26",
    "lic": "PD",
    "cong": 0,
    "chordPro": "Verse 1\nDios nos ha dado promesa:\nlluvias de gracia enviaré,\ndones que os den fortaleza;\ngran bendición os daré.\n\nChorus\nLluvias de gracia,\nlluvias pedemos Señor.\nMándanos lluvias copiosas,\nlluvias del Consolador.\n\nVerse 2\nCristo nos dio la promesa\ndel santo Consola dor,\ndándonos pas y pureza,\npara su gloria y honor.\n\nVerse 3\nMuestra, oh Dios, al creyente\ntodo tu amor y poder,\neres de gracia la fuente,\nllena de paz nuestro ser.\n\nVerse 4\nObra en tus siervos piadosos*\ncele, virtud y valor,\ndándonos dones preciosos,\ndones del Consolador.\n\nVerse 5\n* siervas piadosas"
  },
  {
    "t": "Todas las promesas",
    "a": "R. Kelso Carter · tr. Vicente Mendoza",
    "y": null,
    "th": null,
    "k": null,
    "bpm": null,
    "ts": null,
    "lang": "Spanish",
    "scr": "Juan 2:25",
    "lic": "PD",
    "cong": 0,
    "chordPro": "Verse 1\nTodas las promesas del Señor Jesús\nson apoyo poderoso de mi fe;\nmientras luche aquí buscando yo su luz,\nsiempre en sus promesas confiaré.\n\nChorus\nGrandes, fieles,\nlas promesas que el Señor Jesús ha dado,\nGrandes, fieles,\nen ellas para siempre confiaré.\n\nVerse 2\nTodas las promesas para el hombre fiel,\nel Señor en sus bondades cumplirá.\nY confiando, sé que para siempre en Él,\npaz eterna el mundo gozará."
  },
  {
    "t": "Venid, pastorcillos",
    "a": "Francisco Martínez de la Rosa",
    "y": null,
    "th": null,
    "k": null,
    "bpm": null,
    "ts": null,
    "lang": "Spanish",
    "scr": "Salmos 51:10-17",
    "lic": "PD",
    "cong": 0,
    "chordPro": "Verse 1\nVenid, pastorcillos, venid a adorar\nal Rey de los cielos que nace en Judá.\nSin ricas ofrendas podemos llegar,\nque el niño prefiere la fe y la bondad.\n\nVerse 2\nUn rústico techo abrigo le da;\npor cuna un pesebre, por templo un portal;\nen lecho de pajas incógnito está\nquien quiso a los astros su gloria prestar.\n\nVerse 3\nHermoso lucero le vino a anunciar,\ny magos de Oriente buscándole van;\ndelante se postran del Rey de Judá,\nde incienso, oro y mirra tributo le dan."
  },
  {
    "t": "Yo Escucho, Mi Jesús",
    "a": "Lewis Hartsough · tr. Juan Bautista Cabrera Ivars",
    "y": null,
    "th": null,
    "k": null,
    "bpm": null,
    "ts": null,
    "lang": "Spanish",
    "scr": "Salmos 25:7",
    "lic": "PD",
    "cong": 0,
    "chordPro": "Verse 1\nYo escucho, buen Jesús,\nTu dulce voz de amor,\nQue, desde el árbol de la cruz,\nInvita al pecador.\nYo soy pecador,\nNada hay bueno en mí;\nSer objeto de tu amor\nDeseo, y vengo a ti.\n\nVerse 2\nTú ofreces el perdón\nDe toda iniquidad,\nSi el llanto inunda el corazón\nQue acude a tu piedad.\nYo soy pecador,\nTen de mi piedad.\nDame llanto de dolor,\nY borra mi maldad."
  }
];
