// Generated by tools/import-videos.ts — do not edit by hand.
// One curated YouTube performance per song, verified live via oEmbed at import time.
export interface VideoInfo { id: string; videoTitle: string; }
export const VIDEO_MAP: Record<string, VideoInfo> = {
  "All Creatures of Our God and King": { id: "MUZD0hgtSgE", videoTitle: "All Creatures of Our God and King • Prayers of the Saints Live" },
  "Amazing Grace": { id: "5iou_pSEbEY", videoTitle: "Amazing Grace" },
  "Be Thou My Vision": { id: "ihJAJA4ibEs", videoTitle: "BE THOU MY VISION -- My Favorite Irish Hymn! :)" },
  "Come Thou Fount": { id: "4xJXzgonLdQ", videoTitle: "Come Thou Fount of Every Blessing (with lyrics) The most BEAUTIFUL hymn you've EVER heard!" },
  "Doxology": { id: "tQUTvMtUhw4", videoTitle: "The Doxology | Anthem Lights ft. Selah" },
  "Ein feste Burg ist unser Gott": { id: "nDdHtOSHIXE", videoTitle: "The Wartburg Choir: Ein feste Burg ist unser Gott, arr. W. B. Olds" },
  "Holy, Holy, Holy": { id: "zzM9P_Gqw-s", videoTitle: "Holy, Holy, Holy! Lord God Almighty (Tune: Nicea - 4vv) [with lyrics for congregations] {Robin Mark}" },
  "It Is Well with My Soul": { id: "AHe_qmo3gX4", videoTitle: "It Is Well With My Soul" },
  "Silent Night": { id: "91aX3qBUm6I", videoTitle: "Silent Night (with lyrics) - The most BEAUTIFUL Christmas carol / hymn!" },
  "Stille Nacht": { id: "9p97sxREC00", videoTitle: "Stille Nacht (Silent Night) – Lyric Video" }
};
