import { type Kysely, sql } from "kysely";
import { buildCatalog } from "../seed-data/catalog.js";
import { Environment } from "../helpers/Environment.js";

// Adds lyricsUrl and points catalog songs at their word-timing JSON
// (content/songs/<id>/lyrics.json, generated by tools/generate-lyric-timings.py).
export async function up(db: Kysely<any>): Promise<void> {
  await db.schema.alterTable("songs").addColumn("lyricsUrl", sql`varchar(255)`).execute();

  const { rows } = buildCatalog(Environment.contentRoot);
  for (const row of rows) {
    if (!row.lyricsUrl) continue;
    await db.updateTable("songs").set({ lyricsUrl: row.lyricsUrl }).where("id", "=", row.id).execute();
  }
}

export async function down(db: Kysely<any>): Promise<void> {
  await db.schema.alterTable("songs").dropColumn("lyricsUrl").execute();
}
