import { type Kysely } from "kysely";
import { createPool } from "mysql2/promise";
import { readFileSync } from "node:fs";

// Unpublish Malayalam lyrics-only songs removed from the content library.
// Mirrors the admin unpublish action so votes, saves and sings survive.
const IDS = [
  "-iPOMxK3r9B",
  "-vf9BCAjzKv",
  "-xsTJTw52yX",
  "03CHomHT_cb",
  "0Bgf9zDEC_c",
  "0MCsRWxo0WS",
  "0_RxWSl7ykF",
  "0wKsDOTwmR5",
  "155S31GzAMD",
  "1_c7-APeByg",
  "1ePVtfBz-Gx",
  "1l6I4y4PSKX",
  "1mQYdHgLyG7",
  "1vAljQRUzSM",
  "1wgFl1042_S",
  "21-TKQlTX3R",
  "2RHmuFmn57M",
  "2Zn3gPSXsYj",
  "35Hd_i8gtNY",
  "3kt2E3N_sAX",
  "3wr7TVFG9Ch",
  "4A1dRqFyYe1",
  "4G2u46sRpgj",
  "4IGmwXkad2f",
  "4Kzp83TFNzH",
  "4tyK-OQM6R9",
  "51YICk5mr4Q",
  "5IwHiDu3qoK",
  "5Qc2JMIO9yh",
  "5lx_W4tFvzV",
  "68-xzRp4CV3",
  "6bPyKn4-7ig",
  "6n2eiSLgcXN",
  "6wFDx_ek6U8",
  "7FcYHm5UZ1p",
  "7YPTkzlOfJw",
  "82MUG_bpbuN",
  "868SFh4Re_A",
  "8Udiy0fqQdF",
  "8g21s8h8yct",
  "8kRTerNuvSR",
  "8snN25EzFIp",
  "8wkMGi52bX_",
  "9LiPYeVaEFa",
  "9lteQfaNZfI",
  "9uo00rWevxx",
  "9z5JDIsp1Js",
  "AU7liXcSbJI",
  "BbDneqSfHU9",
  "CVImGtUvDQ8",
  "C_rO7bPPYKM",
  "CqNiW-VChxY",
  "DHMoZYqt_VX",
  "DKXWrdDzGX_",
  "DLQQp8y5o9F",
  "DlSvAwBskG4",
  "Dlx_A4Jb0YV",
  "E4orZLGMz5_",
  "EPF8gwN3iKH",
  "F4XzQ9pmrpN",
  "F6SlVqNu6pp",
  "GO_MLZ3tomD",
  "GZCLompz5fG",
  "GawUm7k7m1f",
  "Gj0TN1-BS7I",
  "IbODiqtjpQi",
  "IwTe-7EX7sh",
  "JGBR8p2HCIv",
  "JKjN0ALi7Rg",
  "Jg6Jay2KKBm",
  "K0hOgdhwUrm",
  "K9N09HA9S1W",
  "KWql9bSIFQD",
  "L02I0O-eP7p",
  "LU4J4qBq4BR",
  "LjrHsi21PEy",
  "LljuT6mA0Ij",
  "LqVny856Y8L",
  "Lw_vj4GT5ef",
  "M8-HnZUu0Qk",
  "MQn3aWDlrWp",
  "MrF_jIqjBuq",
  "N-aW9I-pxm8",
  "N8BmUK5bqjB",
  "NoDHVw2lpPV",
  "NsuRBsAFXwI",
  "NwQf628YO8h",
  "O1LBpkWCOBi",
  "O31PeFoq-eU",
  "OAejfIa4Zrl",
  "OL8UTumkEC3",
  "OVYeCcSZrZj",
  "Oi8zDmbXFh0",
  "P3Fq-xQSwLL",
  "P3VAb6kttDb",
  "PITvGFE6jPI",
  "PKSsi7DaKNq",
  "Pl5GWr7xTbq",
  "PlvOxucRZ0D",
  "QCierDmmoYr",
  "QN37Srh6zOn",
  "Qc2o2KCUhPr",
  "QkiB0fzC7Oa",
  "R3juLq8E7-t",
  "R8lJVWjt0K4",
  "RTJNCMuv_y7",
  "RY3CO0zgPx0",
  "RrgmK4tGDUx",
  "S9xY7zt-4CU",
  "Snm1c9l9d2x",
  "T68sKiAaDxL",
  "THVbjnYhY2l",
  "TMyeVvUhK1s",
  "U_faAub_8vW",
  "V74bTkaMzyJ",
  "VKXsl4BlMT8",
  "VL-tcTbv2hO",
  "VdH68ytVR7S",
  "Vf9M5rttaPw",
  "VskJDGQ3Kr8",
  "Vx0AatMkRZu",
  "W5xOM_3xc4Z",
  "W_MGC3pBqPO",
  "Wi8QLwdH13R",
  "Wp27n0gHxtk",
  "WvlTHmjgGPj",
  "X0I17aPt-q8",
  "XFtcnrOQBKU",
  "Xw54WCT1JBB",
  "YEwjaiXyeD5",
  "YXOoTpTmOMN",
  "YfbpU98UC41",
  "YyG6hz_p-cr",
  "Z7zDrdIP9P6",
  "ZEK8JYX7LQb",
  "ZQT6bldI3KR",
  "ZScDYQ3hib_",
  "ZYvAWWAeefH",
  "ZbrPg7xWjbV",
  "Zv-dcDaKpLG",
  "ZzBKyLwamh6",
  "_2YXeoB83fy",
  "_JLNmgG8rh4",
  "_S8y5FEMPYl",
  "_vyNfKvZBY4",
  "ab6EIQFHaA7",
  "bNoIJ8Lxabv",
  "bVJeQTjMwkp",
  "bbdgoTdYFe1",
  "cE8zfFxyzsC",
  "cGJ9vKAzpbd",
  "cGZ13dAMBTO",
  "cjJGtzdVCbZ",
  "cvN5kKAeret",
  "dagJvjgRAYr",
  "dbmsFUmmDaW",
  "dcVIeT-AVeu",
  "ddgjyT5yH9J",
  "e-6_JMD04zK",
  "eafgbbf9QHs",
  "fHDnk846hg-",
  "fTRLfTeVwlx",
  "fevhiYELaBt",
  "fkLmhbSFuZh",
  "ftpR0RsjnsQ",
  "h4hFBsM9Mki",
  "hN5YrzLoo8M",
  "hPFNS10UzZI",
  "h_2rLiNse0F",
  "hewUSu0jdrw",
  "hmKuL929_Ki",
  "i49BLJVOdz8",
  "iVxdbkr6XG5",
  "j1P7w8tQZwn",
  "jFUYv_-0OLh",
  "jrU0gXVYf40",
  "k-lUNMMhPe9",
  "k-q8eHLjfnP",
  "kW-t1JDGH8R",
  "kWspBN8RSY7",
  "keDGA35HewS",
  "kw5Q-p7UUJk",
  "l3B7bUDrZJx",
  "lw0El5BwlUv",
  "m-JAW6QLRVs",
  "m8BR9mW3HIe",
  "mDcnsPCz4Pq",
  "mIs-Rya9fdP",
  "mKLD6tHk3SN",
  "mOXiMnSG2W8",
  "mQDgkFZ7Hpc",
  "n9HA80eTtB-",
  "nb4-aZvTpZR",
  "oSvwN1K9k-f",
  "oTLMs_qhk4q",
  "ocViHrWtZdQ",
  "p-1qmBzKf4s",
  "pF6AoEfMZZj",
  "pIzshbHuPmz",
  "prB8X_fQyBO",
  "q-S4Cm8RkPT",
  "q12ioAiKybl",
  "qGcK0ZeU9W9",
  "qegpO5NTcjY",
  "qgPtlu3yS05",
  "r8r5idduKJc",
  "rZcuP0zC6SH",
  "rkjcQNnLWOG",
  "sDSQfsko0jT",
  "sK10S8k5T-L",
  "sKwnQsTGweB",
  "sLDtoHk4WxO",
  "sYT5y3IUqWX",
  "s_WOEKj4F8_",
  "slc6RY131di",
  "sqH9JhmPczv",
  "t19iMyD3GXx",
  "tmNko_gfxA-",
  "tv9DUUWPNZM",
  "uAicqEyprAF",
  "uB0_Q_YH8Mp",
  "uB0t_oZFvWw",
  "uL0GXn_HN8j",
  "uPr5QRadh8c",
  "ucwy7Q69IuD",
  "vdKKjcNJKBZ",
  "voBnW8WyZwL",
  "vzqCix8HEox",
  "w1aFIaGCcQR",
  "w2_Upr3fohQ",
  "w6_HqKbrLNM",
  "w9gYRFrv-NC",
  "xA0BwGnibjH",
  "xRfLVGI97q_",
  "xwNjGCxlYyR",
  "yDCLqR-m0qC",
  "yHKT-WMc_OF",
  "yVs7Qdl9WQi",
  "zDDWcSH4yW1",
  "zPq1o1rMFzm",
  "zZ-Jy8-oGl6",
  "zgkNhn8oqtI",
  "znjIgtzQ7t5"
];

export async function up(_db: Kysely<any>): Promise<void> {
  const uri = process.env.COMMONS_CONNECTION_STRING;
  if (!uri) return;
  const catalog = JSON.parse(readFileSync("config/catalog.json", "utf8"));
  const pool = createPool({ uri, charset: "utf8mb4" });
  try {
    const [r] = await pool.query(
      "update assets set status = 'unpublished', unpublishedAt = now(), removedReason = 'uncharted Malayalam lyrics-only' where status = 'published' and id in (?)",
      [IDS]
    );
    console.log(`unpublish_uncharted_malayalam: ${(r as { affectedRows: number }).affectedRows} of ${IDS.length} unpublished`);
    let n = 0;
    for (const row of catalog.rows as any[]) {
      if (!/\[[A-G][#b]?[^\]]*\]/.test(row.chordPro || "")) continue;
      const [u] = await pool.query(
        "update songs set chordPro = ?, songKey = ?, hasChords = 1, confidence = ? where assetId = ? and (hasChords = 0 or hasChords is null or confidence = 'lyrics-only')",
        [row.chordPro, row.songKey, row.confidence, row.id]
      );
      n += (u as { affectedRows: number }).affectedRows;
    }
    console.log(`unpublish_uncharted_malayalam: ${n} chord charts synced`);
  } finally {
    await pool.end();
  }
}

export async function down(): Promise<void> {}
